project_name: promi
release:
  github:
    owner: postfinance
    name: promi
builds:
    - id: promi
      goos:
        - linux
      goarch:
        - amd64
      main: ./cmd/promi/
      binary: promi
      env:
        - CGO_ENABLED=0
nfpms:
    - file_name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}'
      package_name: promi
      replacements:
        "386": 32bit
        amd64: x86_64
        arm: ARM
        arm64: ARM64
        darwin: macOS
        dragonfly: DragonFlyBSD
        freebsd: FreeBSD
        linux: Linux
        netbsd: NetBSD
        openbsd: OpenBSD
        windows: Windows
      formats:
        - deb
        - rpm
      vendor: Die Schweizerische Post - PostFinance
      homepage: https://github.com//postfinance/promcli
      maintainer: Rene Zbinden <rene.zbinden@postfinance.ch>
      description: 'CLI and Web UI to view targets and alerts of multiple prometheus servers.'
      license: Die Schweizerische Post - PostFinance
      bindir: /usr/bin
